name: Scala Snyk

on: workflow_dispatch

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK 11
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '11'

      - name: Run Snyk to check for vulnerabilities 
        uses: snyk/actions/sbt1.10.0-scala3.4.2@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
